### ISSUE TITLE
Not working with angular Cannot find module './ianaAliasMap.json'. 

### ISSUE THREAD

**Issue by jamalhaide** [rubenillodo/windows-iana#24]
Hi,
it's not working with angular Version 10.1.7.
I have installed [Windows-iana](https://www.npmjs.com/package/windows-iana#findIana) but it's not being import and CLI giving the following error.
![image](https://user-images.githubusercontent.com/69233688/115239182-e3ad7100-a137-11eb-8932-e6767511bf35.png)

**Comment by jasonjoh** [comment]
Same issue here. I downgraded to 4.x and it's working.

**Comment by jamalhaide** [comment]
> Same issue here. I downgraded to 4.x and it's working.

Thanks, now it's working.

**Comment by jamalhaide** [comment]
> Same issue here. I downgraded to 4.x and it's working.

**Comment by jasonjoh** [comment]
@jamalhaide I wouldn't close it - this should get fixed in 5.x :D

**Comment by rubenillodo** [comment]
Thanks for reporting this!

**Comment by rubenillodo** [comment]
Would any of you mind installing version `5.0.2-alpha.1` and verifying if everything is OK now? 🥺

**Comment by jasonjoh** [comment]
Just installed it, seems to be working great!

**Comment by rubenillodo** [comment]
Thank you, @jasonjoh. OK, it should be fixed now with version `5.0.2`.
